### ISSUE TITLE
Failed calling webhook "sidecar.inject.juicefs.com"

### ISSUE THREAD

**Issue by KKulishov** [juicedata/juicefs-csi-driver#1007]
## What happened:

I deploy juicefs csi on k8s and use S3 (Minio) as object storage and cockroachdb as metadata engine.
Install JuiceFS helm (this [repo](https://github.com/juicedata/charts/tree/main/charts/juicefs-csi-driver)) and set in values.yaml

```yaml
mountMode: sidecar
```

set labele namespace:

```sh
kubectl label namespace default juicefs.com/enable-injection=true --overwrite
```

when I deploy 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: juicefs-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app
  namespace: default
spec:
  containers:
  - args:
    - -c
    - while true; do echo $(date -u) >> /data/out.txt; sleep 5; done
    command:
    - /bin/sh
    image: busybox
    name: app
    resources:
      limits:
        cpu: 400m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-pvc
```

I get an error 
```sh
Error from server (InternalError): error when creating "test-app-default.yaml": Internal error occurred: failed calling webhook "sidecar.inject.juicefs.com": Post "https://juicefs-admission-webhook.infra.svc:443/juicefs/inject-v1-pod?timeout=5s": x509: certificate is valid for juicefs-admission-webhook, juicefs-admission-webhook.kube-system, juicefs-admission-webhook.kube-system.svc, not juicefs-admission-webhook.infra.svc
```

logs juicefs-csi-controller 

```sh
I0627 07:01:05.410082       7 webhook.go:101] Webhook manager started.
I0627 07:01:05.413950       7 leaderelection.go:248] attempting to acquire leader lease infra/webhook.juicefs.com...
2024/06/27 07:06:42 http: TLS handshake error from 10.42.1.0:19643: remote error: tls: bad certificate
```

Can you tell me how to turn off the TLS. Or skip tls (insecure). how to get around this problem.

**Comment by zwwhdls** [comment]
Try webhook.certManager.enabled = false in values.yaml

**Comment by KKulishov** [comment]
@zwwhdls  thanks for the advice.

But it didn't help

`
helm upgrade --install jucefs --namespace infra ./
Release "jucefs" does not exist. Installing it now.
Error: Unable to continue with install: Secret "juicefs-webhook-certs" in namespace "infra" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "jucefs"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "infra"
`

the problem is in templates/secret.yaml 

this logic

```yaml
{{- $certEnabled := .Values.webhook.certManager.enabled }}

{{- if or (eq .Values.mountMode "sidecar") (.Values.validatingWebhook.enabled)  (eq .Values.mountMode "serverless") }}
{{- if not $certEnabled }}
kind: Secret
apiVersion: v1
metadata:
  name: juicefs-webhook-certs
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: webhook-secret
    {{- include "juicefs-csi.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ b64enc (include "webhook.caBundleCertPEM" .) }}
  tls.crt: {{ b64enc (include "webhook.certPEM" .) }}
  tls.key: {{ b64enc (include "webhook.keyPEM" .) }}
{{- end }}
{{- end }}
```

if remove block in templates/secret.yaml 

then 

```
helm upgrade --install jucefs --namespace infra ./
```

ok

But problems , the problem doesn't go away


and deploy deployment, this error
```sh
Error from server (InternalError): error when creating "test-app-default.yaml": Internal error occurred: failed calling webhook "sidecar.inject.juicefs.com": Post "https://juicefs-admission-webhook.infra.svc:443/juicefs/inject-v1-pod?timeout=5s": x509: certificate is valid for juicefs-admission-webhook, juicefs-admission-webhook.kube-system, juicefs-admission-webhook.kube-system.svc, not juicefs-admission-webhook.infra.svc
```

It's more likely a problem in the logic of the controller's operation. In templates/controller.yaml 
```
{{- if or (eq .Values.mountMode "sidecar") (.Values.validatingWebhook.enabled) (eq .Values.mountMode "serverless") }}
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
        {{- end }}
{{- if or (eq .Values.mountMode "sidecar") (.Values.validatingWebhook.enabled)  (eq .Values.mountMode "serverless")}}
      - name: webhook-certs
        secret:
          secretName: {{ template "juicefs-csi.webhook.secret" . }}
      {{- end }}        
```

When you turn on the webhook, the controller requires the logic of the TLS operation

Can you tell me how to get around this, maybe additionally. argument when launching the controller

**Comment by zwwhdls** [comment]
Do not remove templates/secret.yaml. Try to delete secret `juicefs-webhook-certs`, and reinstall.

**Comment by KKulishov** [comment]
@zwwhdls  I'm sorry, I said it wrong. I didn't remove templates/secret.yaml completely, just juicefs-webhook-certs. 

The installation was successful, but the TLS validation didn’t go anywhere

```
Error from server (InternalError): error when creating "test-app-default.yaml": Internal error occurred: failed calling webhook "sidecar.inject.juicefs.com": Post "https://juicefs-admission-webhook.infra.svc:443/juicefs/inject-v1-pod?timeout=5s": x509: certificate is valid for juicefs-admission-webhook, juicefs-admission-webhook.kube-system, juicefs-admission-webhook.kube-system.svc, not juicefs-admission-webhook.infra.svc
```

It's more likely a problem in the logic of the controller's operation. In templates/controller.yaml

```yaml
{{- if or (eq .Values.mountMode "sidecar") (.Values.validatingWebhook.enabled) (eq .Values.mountMode "serverless") }}
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
        {{- end }}
{{- if or (eq .Values.mountMode "sidecar") (.Values.validatingWebhook.enabled)  (eq .Values.mountMode "serverless")}}
      - name: webhook-certs
        secret:
          secretName: {{ template "juicefs-csi.webhook.secret" . }}
      {{- end }}     
```

You also described the use of a certificate on the controller.  When sidecar mode is on.

**Comment by KKulishov** [comment]
@zwwhdls  The problem is most likely in the logic itself  [this](https://github.com/juicedata/juicefs-csi-driver/blob/master/cmd/controller.go#L176) it is indicated to use tls when used webhook

**Comment by zwwhdls** [comment]
Apiserver restricts communication with the webhook server to use TLS. If you set certManager.enabled = false, helm will auto generate the cert and pem. I double check it works ok. Please delete all related resources (including MutatingWebhookConfiguration, Statefulset juicefs csi controller, Secret juicefs-webhook-certs) and then install it again for retry.

**Comment by KKulishov** [comment]
@zwwhdls 
Thank you. It's work. 

Here's how I did it

```
helm uninstall jucefs --namespace infra
```

and delete old secrets juicefs-webhook-certs and ConfigMaps Webhook 

and  set  in values.yaml

```yaml
webhook:
  # Setup the webhook using cert-manager
  certManager:
    enabled: false
```
and

 helm upgrade --install
