### ISSUE TITLE
[BUG] cannot valid `buffer-size` option when using the config specify the memory limit

### ISSUE THREAD

**Issue by zxh326** [juicedata/juicefs-csi-driver#1074]
configmap

```yaml
   resources:
     limits:
       cpu: 5
       memory: 20Gi

```
buffer-size:
```yaml
- buffer-size=10240Mi
```

error
`
  Warning  FailedMount             10s (x6 over 26s)  kubelet                  MountVolume.SetUp failed for volume "pvc-9e592412-bbb3-4362-8412-54293ea66090" : rpc error: code = Internal desc = Could not mount juicefs: buffer-size 10240 MiB is greater than pod memory limit 5Gi
`
