### ISSUE TITLE
Encryption with csi-driver

### ISSUE THREAD

**Issue by sj14** [juicedata/juicefs-csi-driver#1120]
Hi, I've patched the DaemonSet and added `encrypt_rsa_key` to the secret according to the documentation [1].

However, the juicefs-plugin container reports:

```
node.go:149] NodePublishVolume: mounting juicefs with secret [secret-key storage access-key bucket encrypt_rsa_key format-options metaurl name], options [ro]
juicefs.go:352] Get PV with volumeID <REDACTED> error: k8s client is nil
juicefs.go:984] ceFormat cmd: [/usr/local/bin/juicefs format --storage=s3 --bucket=<REDACTED> --access-key=<REDACTED> --secret-key=${secretkey} ${metaurl} <REDACTED> --trash-days=1 --block-size=4096 --encrypt-rsa-key]
juicefs.go:1004] Format output is ERROR: This command requires at least 2 arguments
```

It seems the encryption key from the secret is not passed to the format command. 

I'm using the following values for the chart:

```
immutable: true
mountMode: process
```

Help is appreciated.

[1] https://juicefs.com/docs/csi/security/encryption

**Comment by zwwhdls** [comment]
Hi, can you provide the secret and version of CSI node ?

**Comment by sj14** [comment]
Thanks for your reply.

The secret looks like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: <NAME>-secret
  namespace: juicefs
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: <NAME>
  metaurl: sqlite3://juicefs-<NAME>.db
  storage: s3
  bucket: https://<REDACTED>
  access-key: <REDACTED>
  secret-key: <REDACTED>
  format-options: trash-days=1,block-size=4096,encrypt-rsa-key
  encrypt_rsa_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
   ...
    -----END OPENSSH PRIVATE KEY-----
```

The RSA key has no passphrase.

The CSI node version is `v0.24.7`.
