### ISSUE TITLE
[BUG] cachedir mountOption conflict with the custom volume

### ISSUE THREAD

**Issue by zxh326** [juicedata/juicefs-csi-driver#1132]
**What happened**:

configmap

```yaml
volumeMounts :
  - name: jfs-cache
    mountPath: /data/cache
volumes :
  - name: jfs-cache
    persistentVolumeClaim:
      claimName: jfs-cache-pvc
```

and with `cachedir=/data/cache` option to create mountpod

will cause mountpod creation failure

error

```
mountPath: Invalid Value: "/data/cache":  must be unique
```

The reason is we will create a hostpath volume for each cachedir option.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
