### ISSUE TITLE
pod mount pvc failed

### ISSUE THREAD

**Issue by yanming-zhang** [juicedata/juicefs-csi-driver#1133]
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/bff702c4-3a4f-45f1-add5-72cd957af6c1">

**Comment by yanming-zhang** [comment]
```
my test pod yaml configure:

apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app
  namespace: eff
spec:
  containers:
  - args:
    - -c
    - while true; do echo $(date -u) >> /data/out.txt; sleep 5; done
    command:
    - /bin/sh
    image: busybox
    name: app
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-pvc
```
