### ISSUE TITLE
[BUG]  static pv, global config Not effective

### ISSUE THREAD

**Issue by wolgod** [juicedata/juicefs-csi-driver#1189]
**What happened**:
 mount pod resource no change

**What you expected to happen**:
user global config resource

**How to reproduce it (as minimally and precisely as possible)**:
1. global config 
```
mountPodPatch:
    - resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 256Mi
     - pvcSelector:
          matchLabels:
            custom-resources: "true"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
```
2. pvc 增加label
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-538424121676009018
  namespace: ns-2263
  lables:
    custom-resources: "true"
```
3.  after delete mount pod，the resource Still cpu 100m mem 256m.

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):0.25.2
- Kubernetes version (e.g. `kubectl version`):1.20.1
- Object storage (cloud provider and region): ceph =
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zwwhdls** [comment]
What is the volumeHandle of PV ?

**Comment by wolgod** [comment]
> What is the volumeHandle of PV ?

pv:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fs-538424121676009018-2263-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: csi.juicefs.com
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-secret
      namespace: juicefs
    volumeAttributes:
      juicefs/clean-cache: "true"
    volumeHandle: fs-538424121676009018-2263-pv
  mountOptions:
  - subdir=/fs-538424121676009018
  - cache-dir=/data/juicefs_cache
  - cache-size=10240
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

pvc

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-538424121676009018
  namespace: ns-2263
  labels:
    custom-resources: "true"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: fs-538424121676009018-2263-pv
```
