### ISSUE TITLE
[BUG] 同时创建和删除大量应用pod时会残留几个没有被删除

### ISSUE THREAD

**Issue by YunhuiChen** [juicedata/juicefs-csi-driver#1229]
**What happened**:
1、创建100个应用pod和mount pod
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dynamic-ee
  labels:
    app: dynamic-ee
spec:
  replicas: 100
  podManagementPolicy: Parallel
  serviceName: dynamic-ee
  selector:
    matchLabels:
      app: dynamic-ee
  template:
    metadata:
      labels:
        app: dynamic-ee
    spec:
      containers:
      - command:
        - sh
        - -c
          # - sleep infinity
        - "while true; do echo $(date -u) >> /data/out.txt; sleep 0.5; done"
        image: registry.cn-hangzhou.aliyuncs.com/juicedata/mount:ce-v1.2.0
        name: tools
        volumeMounts:
        - mountPath: /data
          name: dynamic-ee
          mountPropagation: HostToContainer
  volumeClaimTemplates:
  - metadata:
      name: dynamic-ee
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: dynamic-ee
      resources:
        requests:
          storage: 1Gi
```
2、删除后有残留的应用pod和mount pod没有被正常删除
```
root@chaos-k8s-001:~# k get pods |grep dyn
dynamic-ee-67                                                           0/1     Terminating   0          23m
dynamic-ee-74                                                           0/1     Terminating   0          23m
root@chaos-k8s-001:~# k describe pods dynamic-ee-67
Name:                      dynamic-ee-67
Namespace:                 kube-system
Priority:                  0
Service Account:           default
Node:                      chaos-k8s-001/172.28.39.187
Start Time:                Thu, 09 Jan 2025 11:40:05 +0800
Labels:                    app=dynamic-ee
                           controller-revision-hash=dynamic-ee-97b7b568f
                           juicefs-uniqueid=
                           statefulset.kubernetes.io/pod-name=dynamic-ee-67
Annotations:               cni.projectcalico.org/containerID: be7373b1440b83015e0769d6650ada3b7ff646f68aa1c68e6ab09d20921b9595
                           cni.projectcalico.org/podIP:
                           cni.projectcalico.org/podIPs:
Status:                    Terminating (lasts 16m)
Termination Grace Period:  30s
IP:                        10.1.26.188
IPs:
  IP:           10.1.26.188
Controlled By:  StatefulSet/dynamic-ee
Containers:
  tools:
    Container ID:  docker://333d0fc13b4664cdf5950377037b54e2dd50a1a712f268c4d1229282fdcd14f4
    Image:         registry.cn-hangzhou.aliyuncs.com/juicedata/mount:ce-v1.2.0
    Image ID:      docker-pullable://registry.cn-hangzhou.aliyuncs.com/juicedata/mount@sha256:cc481bb2e24ee4053ff4781fc0369544f33f74558e9e319fe0e5633fc0a31ebb
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      while true; do echo $(date -u) >> /data/out.txt; sleep 0.5; done
    State:          Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 09 Jan 2025 11:43:03 +0800
      Finished:     Thu, 09 Jan 2025 11:47:36 +0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from dynamic-ee (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9qpcn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  dynamic-ee:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  dynamic-ee-dynamic-ee-67
    ReadOnly:   false
  kube-api-access-9qpcn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    23m   default-scheduler  Successfully assigned kube-system/dynamic-ee-67 to chaos-k8s-001
  Warning  FailedMount  21m   kubelet            Unable to attach or mount volumes: unmounted volumes=[dynamic-ee], unattached volumes=[dynamic-ee kube-api-access-9qpcn]: timed out waiting for the condition
  Warning  FailedMount  21m   kubelet            MountVolume.SetUp failed for volume "pvc-62465263-5921-4e0d-b37b-18056b978b97" : rpc error: code = Internal desc = Could not mount juicefs: mount chaos-test at /jfs/pvc-62465263-5921-4e0d-b37b-18056b978b97-zeltek failed: mount isn't ready in 30 seconds
  Warning  FailedMount  21m   kubelet            MountVolume.SetUp failed for volume "pvc-62465263-5921-4e0d-b37b-18056b978b97" : rpc error: code = Unavailable desc = transport is closing
  Normal   Pulled       20m   kubelet            Container image "registry.cn-hangzhou.aliyuncs.com/juicedata/mount:ce-v1.2.0" already present on machine
  Normal   Created      20m   kubelet            Created container tools
  Normal   Started      20m   kubelet            Started container tools
  Normal   Killing      16m   kubelet            Stopping container tools
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
