### ISSUE TITLE
[BUG] create mount pod error because of default toleration error

### ISSUE THREAD

**Issue by zwwhdls** [juicedata/juicefs-csi-driver#1296]
**What happened**:
```
E0312 13:14:30.222876       7 driver.go:107] "GRPC error" err="rpc error: code = Internal desc = Could not mount juicefs: Pod \"juicefs-[10.1.1.81](http://10.1.1.81/)-canoe-sto-cubhtiy710-icsrkb\" is invalid: spec.tolerations[5].key: Invalid value: \"[node.kubernetes.io/unreachable\\x00\\x00](http://node.kubernetes.io/unreachable//x00//x00)\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')" logger="driver"
```

The default toleration inherited from CSI node has special characters `node.kubernetes.io/unreachable\\x00\\x00`

Restarting CSI Node can recover it.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

toleration in CSI Node:

```
  tolerations:
  - operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
```

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`): v1.22.5-tke.8
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
