### ISSUE TITLE
[BUG] Mount pod error when cacheDirs in global config is conflict with cache-dir in option

### ISSUE THREAD

**Issue by zwwhdls** [juicedata/juicefs-csi-driver#1311]
**What happened**:
Mount pod error when cacheDirs in global config is conflict with cache-dir in option

global config:
```
...
        cacheDirs:
          - type: HostPath
            path: /cache
        mountOptions:
          - cache-dir=/cache
...
```

Error in application pod:
```
  Warning  FailedMount  16s               kubelet            MountVolume.SetUp failed for volume "pvc-fe9b3310-3703-4acd-b471-d513a41f1d53" : rpc error: code = Internal desc = Could not mount juicefs: Pod "juicefs-cn-hangzhou.10.0.1.4-pvc-fe9b3310-3703-4acd-b471-d513a41f1d53-jomeco" is invalid: spec.containers[0].volumeMounts[4].mountPath: Invalid value: "/cache": must be unique
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
