### ISSUE TITLE
Improvement for helm chart's output message.

### ISSUE THREAD

**Issue by matrixji** [juicedata/juicefs-csi-driver#164]
I'm installing csi-driver chart with below commands:
```bash
helm upgrade juicefs-csi-driver  juicefs-csi-driver/juicefs-csi-driver --install -f  juicefs_values.yaml
```

and the content of juicefs_values.yaml below:
```yaml
- name: juicefs
  enabled: true
  reclaimPolicy: Retain
  backend:
    name: juicefs
    metaurl: redis://:redis@redis-master.redis.svc
    storage: s3
    accessKey: minio
    secretKey: minio123
    bucket: http://minio-service.default.svc:9000/milvus-test
```

I'm using `juicefs` as the `name` parameter. and I've got the output for test if juicefs is working correctly like below:
```

...

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Pi
  storageClassName: juicefs-sc

...

```

the example using `juicefs-sc` as the storageClassName, but indeed, we create it with the name with `juicefs`.
