### ISSUE TITLE
[DOC] All PVCs have a pod requesting 1 cpu core

### ISSUE THREAD

**Issue by ggaaooppeenngg** [juicedata/juicefs-csi-driver#376]
**Provide a link to that doc page:**

**What is the defect and your suggestions on improvement:**
How to turn off this behavior? If I create many PVCs, the pods' resources cost a lot.

**Comment by zwwhdls** [comment]
Hi @ggaaooppeenngg ,

If the mount pod's resources limit is not explicitly specified in PV, the mount pod will inherit CSI resource. If you donot want to set resource request of mount pod, you can remove resources of CSI daemonset and restart pod. We will update the documentation. thx.

**Comment by ggaaooppeenngg** [comment]
I tested the `-by-process` flag. It mounts PVC without the mount pods. Is this flag being maintained?

**Comment by zwwhdls** [comment]
`by-process` is used in no-kube cluster. It creates juicefs client by process in csi node and mountpoint will be broken when csi restarted or upgraded. `by-process` is not recommended in kube cluster.

**Comment by ggaaooppeenngg** [comment]
```  
node:
    resources:
      limits:
        cpu: 2000m
        memory: 5Gi
      requests:
        cpu: ""
        memory: ""
  controller:
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  storageClasses:
  - backend:
    enabled: true
    name: juicefs-sc
    reclaimPolicy: Retain
    mountPod:
      # mount pod resource requests & limits
      resources:
        limits:
          cpu: 5000m
          memory: 5Gi
        requests:
          cpu: ""
          memory: ""
```
I tried this config, but an empty string is not allowed. How to explicitly clean the resource request?

**Comment by zwwhdls** [comment]
```
node:
    resources:
      limits:
        cpu: 2000m
        memory: 5Gi
  controller:
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  storageClasses:
  - backend:
    enabled: true
    name: juicefs-sc
    reclaimPolicy: Retain
    mountPod:
      # mount pod resource requests & limits
      resources:
        limits:
          cpu: 5000m
          memory: 5Gi
```

Suggest not to set `limit` too. Kubernetes will set `request` same as `limit` when `limit` is specified but `request` not.

Refer to: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits
