### ISSUE TITLE
[BUG] share mount feature not working

### ISSUE THREAD

**Issue by holygrolli** [juicedata/juicefs-csi-driver#405]
**What happened**:
I am trying to use the csi-driver on a small private cluster with limited resources. I am trying to bring `STORAGE_CLASS_SHARE_MOUNT=true` to work. I was trying with v0.16.1 and now v0.17.0 but every pod I start on my single node cluster creates a unique `jfs-mount` pod wasting my resources. 

**What you expected to happen**:
Pods using the same storageClass use the same `jfs-mount` pod on each node

**How to reproduce it (as minimally and precisely as possible)**:
helm-chart-juicefs-csi-driver-0.12.2 with values.yaml:
```
storageClasses:
- name: jfs-idrive
  enabled: true
  reclaimPolicy: Retain
  backend:
    name: idrive
    metaurl: "redis:// # redacted
    storage: s3
    accessKey: # redacted
    secretKey: # redacted
    bucket: # redacted
    # If you need to set the time zone of the JuiceFS Mount Pod, please uncomment the next line, the default is UTC time.
    envs: "{TZ: Europe/Berlin}"
    trashDays: 0
  mountPod:
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "100m"
        memory: 128Mi
  mountOptions:
  - cache-size=2048
node:
  storageClassShareMount: true
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: "100m"
      memory: 128Mi
```
Starting multiple pods with dynamic volume based on your examples:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Pi
  storageClassName: jfs-idrive
---
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app
  namespace: default
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: centos
    name: app
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-pvc
```

**Anything else we need to know?**
I saw this feature being implemented in https://github.com/juicedata/juicefs-csi-driver/pull/321 but after digging through the code with my limited Go knowledge it could be somehow related to creating/using the [settings hash](https://github.com/juicedata/juicefs-csi-driver/blob/0aecb15a911851731f83a29e2342fb82f84428f6/pkg/juicefs/mount/pod_mount.go#L261) which might change because of any property in the struct

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): v0.17.0
- Kubernetes version (e.g. `kubectl version`): v1.23.6+k3s1
- Object storage (cloud provider and region): s3 compatible
- Metadata engine info (version, cloud provider managed or self maintained): keydb
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 
- Others:

**Comment by holygrolli** [comment]
what I realized while further testing: those two mount pods share the same cache-directory on the host. It's because of the the volume UUID of juicefs. does this somehow interfere with `--writeback` option. Which juicefs client is responsible for uploading this?

**Comment by zwwhdls** [comment]
Hi @holygrolli , we'll look into this. Clients with `--writeback` option sharing same cache-dir will all upload datas. Keep any one of them is ok.

**Comment by holygrolli** [comment]
I now removed the Helm managed secret and `StorageClass` so I can provide you with a simpler example:
```
apiVersion: v1
stringData:
    access-key:
    bucket: https://
    envs: '{TZ: Europe/Berlin}'
    format-options: trash-days=0
    metaurl: redis://
    name: idrive
    secret-key:
    storage: s3
kind: Secret
metadata:
    name: jfs-idrive-secret
    namespace: kube-system
type: Opaque
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jfs-idrive
mountOptions:
- free-space-ratio=0.2
- writeback
parameters:
  csi.storage.k8s.io/node-publish-secret-name: jfs-idrive-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: jfs-idrive-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  juicefs/mount-cpu-limit: "1"
  juicefs/mount-cpu-request: 100m
  juicefs/mount-delete-delay: 30s
  juicefs/mount-memory-limit: 512Mi
  juicefs/mount-memory-request: 128Mi
  pathPattern: ${.PVC.namespace}-${.PVC.name}
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Pi
  storageClassName: jfs-idrive
---
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app
  namespace: default
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: centos
    name: app
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc2
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Pi
  storageClassName: jfs-idrive
---
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app2
  namespace: default
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: centos
    name: app
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-pvc2
```
