### ISSUE TITLE
[BUG] Can't bind PVCs with Minio - context timeout

### ISSUE THREAD

**Issue by jrcichra** [juicedata/juicefs-csi-driver#406]
**What happened**:
I made a `StorageClass` that points to a `Secret` with `storage: minio`. I put in the credentials to a minio server that is accessible and the credentials are valid. I also tried with `envs: "{AWS_REGION: abcd }"`.
**What you expected to happen**:
JuiceFS could communicate with the minio server and bind the PVC.
**How to reproduce it (as minimally and precisely as possible)**:
Connect a minio bucket to JuiceFS.
**Anything else we need to know?**
Metadata is using CockroachDB, but that's working fine with a different data backend.
This is running with the arm modifications: https://juicefs.com/docs/csi/csi-in-arm64/#2-install-via-kubectl
When I run `telnet` within `juicefs-csi-controller-o/juicefs-plugin` I get a TCP connection to my minio data endpoint.

Sample Manifest:
```
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-sc-secret-minio
  namespace: kube-system
type: Opaque
stringData:
  name: "minio"
  metaurl: "postgres://root@cockroachdb.cockroachdb:26257/juicefs?sslmode=disable"
  storage: "minio"
  bucket: "http://minio.minio:9000/juicefs"
  access-key: "juicefs"
  secret-key: "REDACTED"
  envs: "{AWS_REGION: oracle }"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-minio
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-sc-secret-minio
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: juicefs-sc-secret-minio
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
```

Output:
```
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.769071       1 controller.go:1317] provision "justin/web-pvc" class "juicefs-minio": started
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.769391       1 controller.go:573] CreateVolumeRequest {Name:pvc-bf81ebcc-0974-4ef0-a186-04f8733ffff4 CapacityRange:required_bytes:11258999068426240  VolumeCapabilities:[mount:<> access_mode:<mode:MULTI_NODE_MULTI_WRITER > ] Parameters:map[csi.storage.k8s.io/node-publish-secret-name:juicefs-sc-secret-minio csi.storage.k8s.io/node-publish-secret-namespace:kube-system csi.storage.k8s.io/provisioner-secret-name:juicefs-sc-secret-minio csi.storage.k8s.io/provisioner-secret-namespace:kube-system] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.770594       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"justin", Name:"web-pvc", UID:"bf81ebcc-0974-4ef0-a186-04f8733ffff4", APIVersion:"v1", ResourceVersion:"44339926", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "justin/web-pvc"
juicefs-csi-controller-0 juicefs-plugin I0827 19:22:19.802942       7 controller.go:69] CreateVolume: Secrets contains keys [envs metaurl name secret-key storage access-key bucket env]
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.801408       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
juicefs-csi-controller-0 csi-provisioner I0827 19:22:19.801448       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":11258999068426240},"name":"pvc-bf81ebcc-0974-4ef0-a186-04f8733ffff4","secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":5}}]}
juicefs-csi-controller-0 juicefs-plugin I0827 19:22:19.803466       7 juicefs.go:626] ceFormat cmd: [/usr/local/bin/juicefs format --storage=minio --bucket=https://minio.minio:9000/juicefs --access-key=juicefs --secret-key=${secretkey} ${metaurl} minio]
juicefs-csi-controller-0 liveness-probe I0827 19:22:24.634134       1 connection.go:153] Connecting to unix:///csi/csi.sock
juicefs-csi-controller-0 juicefs-plugin I0827 19:22:24.804764       7 juicefs.go:647] Format output is 
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.805714       1 connection.go:185] GRPC response: {}
juicefs-csi-controller-0 juicefs-plugin E0827 19:22:24.804904       7 driver.go:83] GRPC error: rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.805881       1 connection.go:186] GRPC error: rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.805955       1 controller.go:645] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.806115       1 controller.go:1084] Final error received, removing PVC bf81ebcc-0974-4ef0-a186-04f8733ffff4 from claims in progress
juicefs-csi-controller-0 csi-provisioner W0827 19:22:24.807358       1 controller.go:943] Retrying syncing claim "bf81ebcc-0974-4ef0-a186-04f8733ffff4", failure 7
juicefs-csi-controller-0 csi-provisioner E0827 19:22:24.807458       1 controller.go:966] error syncing claim "bf81ebcc-0974-4ef0-a186-04f8733ffff4": failed to provision volume with StorageClass "juicefs-minio": rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 csi-provisioner I0827 19:22:24.806325       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"justin", Name:"web-pvc", UID:"bf81ebcc-0974-4ef0-a186-04f8733ffff4", APIVersion:"v1", ResourceVersion:"44339926", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "juicefs-minio": rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = rpc error: code = Internal desc = context timeout
juicefs-csi-controller-0 liveness-probe I0827 19:22:34.635071       1 connection.go:153] Connecting to unix:///csi/csi.sock
juicefs-csi-controller-0 liveness-probe I0827 19:22:44.633771       1 connection.go:153] Connecting to unix:///csi/csi.sock
juicefs-csi-controller-0 liveness-probe I0827 19:22:54.634751       1 connection.go:153] Connecting to unix:///csi/csi.sock
```

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):  The ones listed here: https://juicefs.com/docs/csi/csi-in-arm64/#2-install-via-kubectl
- Kubernetes version (e.g. `kubectl version`): v1.24.2+k3s2
- Object storage (cloud provider and region): minio running in same K3S cluster behind a `Service`
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): All within k3s. CockroachDB metadata, minio data.
- Others:
