### ISSUE TITLE
[QUESTION]  transport endpoint is not connected    when using with es

### ISSUE THREAD

**Issue by hb407033** [juicedata/juicefs-csi-driver#490]
##   deploy es single data node using juicefs csi， but can`t start
this is logs  es init container log
![image](https://user-images.githubusercontent.com/10432196/205496730-0fec9133-33af-4aa5-9fd1-f816648e188a.png)

this is es server log 
![image](https://user-images.githubusercontent.com/10432196/205496744-54e8f587-e42d-4fc5-b3e5-c2f881f2d353.png)

this is logs in es  explain api log shows
![image](https://user-images.githubusercontent.com/10432196/205496598-334b40f5-ae2e-4b1a-9552-872fd13c0ff5.png)

this is mount pod`s logs 
![image](https://user-images.githubusercontent.com/10432196/205496683-a4baeb7d-2df2-4eb6-ba11-c6fcb44ce50f.png)

i tried to restart es by delete data pod, but also same, please help me

**Comment by zwwhdls** [comment]
Hi @hb407033 , the log shows "Transport endpoint is not connected". It means mount point is broken. Please check whether the mount pod is the exact one which es pod used, refering to [this doc](https://juicefs.com/docs/zh/csi/troubleshooting#check-mount-pod). In addtion, you can check mount point in es pod by `df`.

**Comment by hb407033** [comment]
the last pic show the mount pod`s log,  seems nothing is wrong
the mound has no event   as followed by  advised doc link

![image](https://user-images.githubusercontent.com/10432196/205551207-edfc8630-c6ed-47d9-822d-a370df4b24f1.png)
kubec

df shows  same "transport endpoint is not connected"

![image](https://user-images.githubusercontent.com/10432196/205551384-8aa15c4a-8fb3-4b8c-a120-339f81a00729.png)

**Comment by zwwhdls** [comment]
Can you also provide the es yaml & PVC yaml?

**Comment by hb407033** [comment]
the links  shows the  statefulset yml

[es.txt](https://github.com/juicedata/juicefs-csi-driver/files/10151921/es.txt)

**Comment by zwwhdls** [comment]
Hi, I saw the PVC status is pending, can you check the event of PVC which es used? 

```
kubectl describe pvc elasticsearch-logging-data-0
```

**Comment by hb407033** [comment]
pvc is bound
![image](https://user-images.githubusercontent.com/10432196/205595628-3fb22762-9bc4-4d47-99ff-8f95d27d695a.png)

**Comment by zwwhdls** [comment]
If you don't mind, can you execute a diagnostic script to collect the information we need referring to [this doc](https://juicefs.com/docs/zh/csi/troubleshooting#%E8%AF%8A%E6%96%AD%E8%84%9A%E6%9C%AC).

**Comment by hb407033** [comment]
i checked other clusters,   and the stst`s pvc  is  `pending` status

**Comment by hb407033** [comment]
this is the diagnoise logs 
[diagnose_juicefs_1670232273.tar.gz](https://github.com/juicedata/juicefs-csi-driver/files/10152707/diagnose_juicefs_1670232273.tar.gz)

**Comment by zwwhdls** [comment]
Hi, we found that mount pod is oom upon it started and restarted successfully:

```
  containerStatuses:
  - containerID: docker://2d8bf8a6bef322bc1935992d950106f37b366a6acaa52dab6473cbfb2546842c
    image: harbor.dev.xjyt.petrochina/k8s/juicefs-mount:v1.0.0-4.8.0
    imageID: docker-pullable://harbor.dev.xjyt.petrochina/k8s/juicefs-mount@sha256:fae2cc6280f06391c3e4d28214503f881fb2887fcc3b1021fd0ae9ef2b4c5413
    lastState:
      terminated:
        containerID: docker://b2ff0c34d5020f3fc288512491e328c7ce07c3cdec1da2832ced33e1ee6307e1
        exitCode: 137
        finishedAt: "2022-12-05T02:09:51Z"
        reason: OOMKilled
        startedAt: "2022-12-04T07:34:01Z"
    name: jfs-mount
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2022-12-05T02:09:52Z"
```

Mount pod's default resource limit is 2c5g, you can update it referring to [this doc](https://juicefs.com/docs/zh/csi/guide/resource-optimization/#mount-pod-resources). 

Besides, you can enable mountpoint recover automatically,  referring to [this doc](https://juicefs.com/docs/zh/csi/guide/pv#automatic-mount-point-recovery)
