### ISSUE TITLE
[FEATURE] Add port for prometheus monitoring to mount pod definition

### ISSUE THREAD

**Issue by dbotwinick** [juicedata/juicefs-csi-driver#529]
**What feature you'd like to add:**
Add port for prometheus monitoring to juicefs-mount pod definition(s)

Would just require a small addition for the containers spec...

```
    ports:
      - containerPort: 9567
        name: prometheus

```
**Why is this feature needed:**
Would facilitate easy prometheus monitoring via PodMonitor CRD from the prometheus-operator

Example PodMonitor definition...

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: juicefs-mounts-monitor
  namespace: monitoring
  labels:
    name: juicefs-mounts-monitor
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: juicefs-mount
  podMetricsEndpoints:
    - targetPort: prometheus
      path: '/metrics'
      scheme: 'http'
      interval: '5s'
```
**Other Considerations**
Would require updating port if the port is otherwise configured and would require disabling port if monitoring features are disabled.

**Comment by robgordon89** [comment]
@dbotwinick this was reworked and released a few days ago and works nicely on my cluster 👍 

The only thing that changed was the port name.

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: juicefs-mounts-monitor
  namespace: monitoring
  labels:
    name: juicefs-mounts-monitor
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: juicefs-mount
  podMetricsEndpoints:
    - targetPort: metrics
      path: "/metrics"
      scheme: "http"
      interval: "5s"
```
