### ISSUE TITLE
[BUG] Should reject PVC with `volumeMode: Block`

### ISSUE THREAD

**Issue by fungaren** [juicedata/juicefs-csi-driver#604]
**What happened**:

I am using Kubernetes [e2e testing framework](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external) to test the juicefs-csi-driver. Unfortunately I found `volumeMode` testing is failed because the controller didn't reject PVC with `volumeMode: Block`. The e2e test say (with Kubernetes version v1.26.0, you should use this version to get the correct line):

```text
• [FAILED] [130.440 seconds]
External Storage [Driver: juicefs-csi-driver]
test/e2e/storage/external/external.go:173
  [Testpattern: Dynamic PV (block volmode)] volumeMode
  test/e2e/storage/framework/testsuite.go:50
    [It] should fail in binding dynamic provisioned PV to PVC [Slow][LinuxOnly]
    test/e2e/storage/testsuites/volumemode.go:260
...
  Mar 21 10:41:20.261: PVC phase isn't pending
  Expected
      <v1.PersistentVolumeClaimPhase>: Bound
  to equal
      <v1.PersistentVolumeClaimPhase>: Pending
  In [It] at: test/e2e/storage/testsuites/volumemode.go:292
```

**What you expected to happen**:

Should reject PVC with `volumeMode: Block`.

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce it, you should apply this PVC:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: should-fail-pvc
  namespace: default
spec:
  # Do not support block mode, should fail!
  volumeMode: Block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Pi
  storageClassName: juicefs-root-bucket
```

Then the PV provisioning succeeds:

```text
$ kubectl get pvc -A
NAMESPACE   NAME              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
default     should-fail-pvc   Bound    pvc-1144bfac-5062-4c17-ace0-aff46f0963ca   10Pi       RWX            juicefs-root-bucket   8m55s
```

But actually the PV is unusable, try this Pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app-block
  namespace: default
spec:
  containers:
  - args:
    - -c
    - while true; do sleep 5; done
    command:
    - /bin/sh
    image: busybox:musl
    name: app
    volumeDevices:
    - devicePath: /dev/blk0
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: should-fail-pvc
  terminationGracePeriodSeconds: 5
```

Stuck on `ContainerCreating`, see its events:

```text
Events:
  Type     Reason           Age               From               Message
  ----     ------           ----              ----               -------
  Normal   Scheduled        40s               default-scheduler  Successfully assigned default/juicefs-app-block to debian
  Warning  FailedMapVolume  8s (x7 over 40s)  kubelet            MapVolume.MapPodDevice failed for volume "pvc-1144bfac-5062-4c17-ace0-aff46f0963ca" : rpc error: code = Internal desc = Could not mount juicefs: target kubelet rootdir /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-1144bfac-5062-4c17-ace0-aff46f0963ca/ce7c2090-a278-4af5-8a03-8f6178c7a301 is not equal csi mounted kubelet root-dir /var/lib/kubelet
```

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
