### ISSUE TITLE
seems like not support mount option like allow-other

### ISSUE THREAD

**Issue by mahonzhan** [juicedata/juicefs-csi-driver#64]
something like the "mountOptions", yaml below:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-sc
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
mountOptions:
  - allow-other
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-6hh8cg24g8
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: juicefs-6hh8cg24g8
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
provisioner: csi.juicefs.com
```
