### ISSUE TITLE
[BUG] delvol image should inherit mount-image

### ISSUE THREAD

**Issue by timfeirg** [juicedata/juicefs-csi-driver#642]
**What happened**: `juicefs/mount-image` is already set, but delvol pod is still using the default container

**Comment by fungaren** [comment]
Yes I met this problem just now. 

```text
kubectl get pod/juicefs-ea3fc228-cleancache-tlwxsr-zmfbs -nkube-system -oyaml
...
    image: juicedata/mount:ee-4.9.1
```

Currently, the work around is to set `JUICEFS_MOUNT_IMAGE` environment to CSI Node & CSI Controller:

```yaml
        - name: JUICEFS_CE_MOUNT_IMAGE
          value: juicedata/mount:v1.0.4-4.9.0
        - name: JUICEFS_MOUNT_IMAGE
          value: juicedata/mount:v1.0.4-4.9.0
```
