### ISSUE TITLE
[BUG] PVC capacity expand doesn't work correctly

### ISSUE THREAD

**Issue by leef627** [juicedata/juicefs-csi-driver#717]
**What happened**:I created a 10G pvc and mount it in a pod, and then I expanded the pvc to 100G. At this time, df in the pod shown that the capacity of the pvc has become 100g, but I recreate the pod and remount the same pvc, the capacity has changed back to 10g

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

create a pvc
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-sc-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: juicefs-sc
```
create a pod and mount pvc
```
---
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-sc-demo-pod
spec:
  containers:
    - command:
      - /bin/sleep
      - inf
      name: juicefs
      image: xxx/juicedata/mount:ce-v1.1.0-beta2-pacific (build by https://github.com/juicedata/juicefs-csi-driver/blob/master/docker/ceph-0.18.juicefs.Dockerfile)
      volumeMounts:
        - name: juicefs-sc-pvc
          mountPath: /mnt/juicefs-sc-pvc
  volumes:
    - name: juicefs-sc-pvc
      persistentVolumeClaim:
        claimName: juicefs-sc-pvc
```
```
root@juicefs-sc-demo-pod:/workspace# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                  2.2T  864G  1.3T  40% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     32G     0   32G   0% /sys/fs/cgroup
JuiceFS:juicefs-rados     10G     0   10G   0% /mnt/juicefs-sc-pvc
/dev/mapper/centos-root  2.2T  864G  1.3T  40% /etc/hosts
shm                       64M     0   64M   0% /dev/shm
tmpfs                     63G   12K   63G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     32G     0   32G   0% /proc/acpi
tmpfs                     32G     0   32G   0% /proc/scsi
tmpfs                     32G     0   32G   0% /sys/firmware
```
expand pvc to 100G
```
root@juicefs-sc-demo-pod:/workspace# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                  2.2T  864G  1.3T  40% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     32G     0   32G   0% /sys/fs/cgroup
JuiceFS:juicefs-rados    100G     0  100G   0% /mnt/juicefs-sc-pvc
/dev/mapper/centos-root  2.2T  864G  1.3T  40% /etc/hosts
shm                       64M     0   64M   0% /dev/shm
tmpfs                     63G   12K   63G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     32G     0   32G   0% /proc/acpi
tmpfs                     32G     0   32G   0% /proc/scsi
tmpfs                     32G     0   32G   0% /sys/firmware
```
recreate the pod and remount the same pvc,the capacity has changed back to 10g
```
root@juicefs-sc-demo-pod:/workspace# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                  2.2T  864G  1.3T  40% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     32G     0   32G   0% /sys/fs/cgroup
JuiceFS:juicefs-rados     10G     0   10G   0% /mnt/juicefs-sc-pvc
/dev/mapper/centos-root  2.2T  864G  1.3T  40% /etc/hosts
shm                       64M     0   64M   0% /dev/shm
tmpfs                     63G   12K   63G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     32G     0   32G   0% /proc/acpi
tmpfs                     32G     0   32G   0% /proc/scsi
tmpfs                     32G     0   32G   0% /sys/firmware
```

**Anything else we need to know?**
I think this has something to do with the capacity parameter in volumeAttributes. After expansion, this parameter has not been modified correctly.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.juicefs.com
    volume.kubernetes.io/provisioner-deletion-secret-name: juicefs-sc-secret
    volume.kubernetes.io/provisioner-deletion-secret-namespace: kube-system
  creationTimestamp: "2023-08-11T07:33:54Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-xxx
  resourceVersion: "xxx"
  selfLink: /api/v1/persistentvolumes/pvc-xxx
  uid: xxx
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: juicefs-sc-pvc
    namespace: default
    resourceVersion: "xxx"
    uid: xxx
  csi:
    controllerExpandSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
    driver: csi.juicefs.com
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
    volumeAttributes:
      capacity: "10737418240"
      juicefs/mount-cpu-limit: 5000m
      juicefs/mount-cpu-request: 1000m
      juicefs/mount-memory-limit: 5Gi
      juicefs/mount-memory-request: 1Gi
      storage.kubernetes.io/csiProvisionerIdentity: 1691725968620-8081-csi.juicefs.com
      subPath: pvc-xxx
    volumeHandle: pvc-xxx
  persistentVolumeReclaimPolicy: Delete
  storageClassName: juicefs-sc
  volumeMode: Filesystem
status:
  phase: Bound
```

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):v0.21.0
- Kubernetes version (e.g. `kubectl version`): v1.22.15
- Object storage (cloud provider and region):ceph rados
- Metadata engine info (version, cloud provider managed or self maintained):tikv 5.4
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 10Gbps*2 bond
- Others:
