### ISSUE TITLE
[BUG] Secret Finalizer doesn't release if retain reclaimPolicy

### ISSUE THREAD

**Issue by kyungwan-nam** [juicedata/juicefs-csi-driver#734]
**What happened**:

``secretFinalizer`` (https://github.com/juicedata/juicefs-csi-driver/issues/707) does not release if ``retain`` ReclaimPolicy.

**What you expected to happen**:

the finalizer on the secret must be release when removing related pvc.

**How to reproduce it (as minimally and precisely as possible)**:

storageclass with ``reclaimPolicy: Retain``, ``secretFinalizer: "true"``

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs
provisioner: csi.juicefs.com
parameters:
...
  # requires the juicefs-provisioner
  secretFinalizer: "true"
  # requires the juicefs-provisioner
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
allowVolumeExpansion: true
reclaimPolicy: Retain
```

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
