### ISSUE TITLE
[BUG][master]: failed to expand volume when using the AWS S3 as the storage backend

### ISSUE THREAD

**Issue by ericsyh** [juicedata/juicefs-csi-driver#767]
**What happened**:

I followed the doc https://juicefs.com/docs/community/juicefs_on_k3s/ to setup the juicefs csi on an AWS EKS cluster and using the AWS S3 as the storage and AWS ElasticCache as the metadata storage. 

I installed the juicefs csi driver by `https://raw.githubusercontent.com/juicedata/juicefs-csi-driver/master/deploy/k8s.yaml`

And created the storage class by 

```
apiVersion: v1
kind: Secret
metadata:
  name: juicefs-sc-secret
  namespace: kube-system
type: Opaque
stringData:
  name: "juicefs-sc-secret"
  metaurl: "redis://erxxxxxx-redis.igijgq.ng.0001.usw2.cache.amazonaws.com:6379"
  storage: "s3"
  bucket: "https://xxxxx-juice-bucket.s3.us-west-2.amazonaws.com"
  access-key: "{ IAM User AK }"
  secret-key: "{ IAM User SK }"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-sc
provisioner: csi.juicefs.com
reclaimPolicy:  Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-sc-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: juicefs-sc-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
```
I created the deployment with example config https://juicefs.com/docs/community/juicefs_on_k3s/#use-juicefs-to-persist-nginx-data

And then I modified the PVC to expand the `spec.resources.requests.storage` and apply but I got error information from the PVC as 

```
Events:
  Type     Reason                 Age                     From                                                                           Message
  ----     ------                 ----                    ----                                                                           -------
  Normal   WaitForFirstConsumer   14m                     persistentvolume-controller                                                    waiting for first consumer to be created before binding
  Normal   ExternalProvisioning   14m (x2 over 14m)       persistentvolume-controller                                                    waiting for a volume to be created, either by external provisioner "csi.juicefs.com" or manually created by system administrator
  Normal   Provisioning           14m                     csi.juicefs.com_juicefs-csi-controller-0_58fba64f-1dbf-4db5-b5a9-7ecaba3cb95c  External provisioner is provisioning volume for claim "default/web-pvc"
  Normal   ProvisioningSucceeded  14m                     csi.juicefs.com_juicefs-csi-controller-0_58fba64f-1dbf-4db5-b5a9-7ecaba3cb95c  Successfully provisioned volume pvc-7c419b05-c6d0-4ffb-b0f3-f69c95709924
  Warning  ExternalExpanding      8m44s                   volume_expand                                                                  waiting for an external controller to expand this PVC
  Normal   Resizing               2m55s (x13 over 8m44s)  external-resizer csi.juicefs.com                                               External resizer is resizing volume pvc-7c419b05-c6d0-4ffb-b0f3-f69c95709924
  Warning  VolumeResizeFailed     2m55s (x13 over 8m44s)  external-resizer csi.juicefs.com                                               resize volume "pvc-7c419b05-c6d0-4ffb-b0f3-f69c95709924" by resizer "csi.juicefs.com" failed: rpc error: code = Internal desc = set quota: rpc error: code = InvalidArgument desc = Nil secrets
```

**What you expected to happen**:

I searched and seems the volume expanding is supported on the csi driver and should expected to the volume expand to the new size. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**: AWS EKS
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): master
- Kubernetes version (e.g. `kubectl version`):

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.6-eks-f8587cb", GitCommit:"b6911bf9eade7d8ca7dd82af5e80626965829947", GitTreeState:"clean", BuildDate:"2023-09-18T22:12:19Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Object storage (cloud provider and region): AWS S3, region us-west-2
- Metadata engine info (version, cloud provider managed or self maintained): Redis 7.0.7, AWS ElasticCache
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
