### ISSUE TITLE
[QUESTION] mount point type of sidecar mode

### ISSUE THREAD

**Issue by enuoCM** [juicedata/juicefs-csi-driver#829]
Hi, what's the default mount point type of sidecar mode? emptyDir? 
Is it ok to use 'Memory' medium type emptyDir?

**Comment by zwwhdls** [comment]
The default mount point of sidecar mode is HostPath and emptyDir does not work.

**Comment by enuoCM** [comment]
Thanks，why emptyDir does not work？
Is any other supported mode?

**Comment by enuoCM** [comment]
> The default mount point of sidecar mode is HostPath and emptyDir does not work.

@zwwhdls 

I made a test. Configure as follows:
```
containers:
    - name: app
    volumeMounts:
      - mountPath: /data
        name: shared-data
        mountPropagation: Bidirectional
    securityContext:
      privileged: true
      runAsUser: 0
...
    - name: jfs-mount
    volumeMounts:
    - mountPath: /jfs
      name: shared-data
      mountPropagation: Bidirectional
    securityContext:
      privileged: true
      runAsUser: 0
...
  volumes:
  - name: shared-data
    emptyDir:
      medium: Memory
...
```

Container 'app' can access the mount point '/jfs' normally.  For this mode, are there any other things to consider？Thanks.

**Comment by zwwhdls** [comment]
Hi @enuoCM ,

In your test, is `/jfs` the mount point of `jfs-mount` container?

The sidecar needs to pass the mount point into the business container and ensure that the `/data` is the mount point. For example, in this config:

```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
  - command:
    - sh
    - -c
    - |-
      /usr/bin/juicefs auth ...
      /sbin/mount.juicefs test-fluid-2 /jfs -o foreground,no-update
    ...
    volumeMounts:
    - mountPath: /jfs
      mountPropagation: Bidirectional
      name: shared-data
  - image: centos:7
    name: tools
    volumeMounts:
    - mountPath: /home/user/data
      name: shared-data
  ...
  volumes:
  - name: shared-data
    emptyDir: {}
```

`jfs-mount` and `tools` container shares the same volume `shared-data` which is emtpyDir, and `jfs-mount` should pass the mount point to `/home/user/data` in `tools`. And the result of above is:

```
[root@iZbp1blzs0ixh12sfj9b2aZ normal]# kubectl exec -it test -c jfs-mount -- bash
root@test:/app# df -h
Filesystem            Size  Used Avail Use% Mounted on
overlay               118G   90G   24G  80% /
tmpfs                  64M     0   64M   0% /dev
tmpfs                 7.6G     0  7.6G   0% /sys/fs/cgroup
tmpfs                  13G   16K   13G   1% /check_mount.sh
/dev/nvme0n1p1        118G   90G   24G  80% /etc/hosts
shm                    64M     0   64M   0% /dev/shm
tmpfs                  13G   12K   13G   1% /run/secrets/kubernetes.io/serviceaccount
JuiceFS:test-fluid-2   10P  332K   10P   1% /jfs
root@test:/app# exit
[root@iZbp1blzs0ixh12sfj9b2aZ normal]# kubectl exec -it test -c tools -- bash
[root@test /]#
[root@test /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         118G   90G   24G  80% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.6G     0  7.6G   0% /sys/fs/cgroup
/dev/nvme0n1p1  118G   90G   24G  80% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs            13G   12K   13G   1% /run/secrets/kubernetes.io/serviceaccount
[root@test /]#
```

From the result, we can see it doesn't work.


In our solution, the pod after sidecar injected is as follows:

```
apiVersion: v1
kind: Pod
metadata:
  namespace: default
spec:
  containers:
  - command:
    - sh
    - -c
    - |-
      /usr/bin/juicefs auth ...
      /sbin/mount.juicefs test-fluid-2 /jfs/fpudle -o foreground,no-update
    ...
    name: jfs-mount
    volumeMounts:
    - mountPath: /jfs
      mountPropagation: Bidirectional
      name: jfs-dir
  - image: centos:7
    name: tools
    volumeMounts:
    - mountPath: /home/user/data
      name: shared-data
  volumes:
  - hostPath:
      path: /var/lib/juicefs/volume/fpudle
      type: ""
    name: shared-data
  - hostPath:
      path: /var/lib/juicefs/volume
      type: DirectoryOrCreate
    name: jfs-dir
```

`jfs-mount` mounted the parent directory `/var/lib/juicefs/volume` which is hostPath and make the `/var/lib/juicefs/volume/fpudle` mountpoint in host. And then `tools` mounted `/var/lib/juicefs/volume/fpudle`, so it can directly see that `/home/user/data` is the mountpoint by `df -h`.

**Comment by enuoCM** [comment]
Hi @zwwhdls 
In my test,  in fact, /jfs/share is the mount point of jfs-mount container.

```
[root@k8s-master juicefs]# kgp -n test-juicefs
NAME                                  READY   STATUS    RESTARTS   AGE
juicefs-app-sidecar-emptydir-memory   2/2     Running   0          3d19h
juicefs-db-d59f4f468-chptp            1/1     Running   0          6d11h
[root@k8s-master juicefs]# k exec -it juicefs-app-sidecar-emptydir-memory bash -c jfs-mount -n test-juicefs
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@juicefs-app-sidecar-emptydir-memory:/# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   50G   24G   27G  48% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     16G     0   16G   0% /sys/fs/cgroup
tmpfs                     10M     0   10M   0% /jfs
/dev/mapper/centos-root   50G   24G   27G  48% /var/jfsCache
tmpfs                     32G  4.0K   32G   1% /root/.rsa
shm                       64M     0   64M   0% /dev/shm
tmpfs                     32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount
JuiceFS:mcjfs1           1.0P  2.1G  1.0P   1% /jfs/share
root@juicefs-app-sidecar-emptydir-memory:/# exit
exit
[root@k8s-master juicefs]# k exec -it juicefs-app-sidecar-emptydir-memory bash -c app -n test-juicefs
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[root@juicefs-app-sidecar-emptydir-memory /]# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   50G   24G   27G  48% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     16G     0   16G   0% /sys/fs/cgroup
tmpfs                     10M     0   10M   0% /data
/dev/mapper/centos-root   50G   24G   27G  48% /etc/hosts
shm                       64M     0   64M   0% /dev/shm
tmpfs                     32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount
JuiceFS:mcjfs1           1.0P  2.1G  1.0P   1% /data/share
```

Can you add `mountPropagation: Bidirectional` to  `tools` container also and try again?

**Comment by zwwhdls** [comment]
Hi @enuoCM , what I meant is the mount point in tools container should be `/data`, not `/data/share`.

**Comment by enuoCM** [comment]
> Hi @enuoCM , what I meant is the mount point in tools container should be `/data`, not `/data/share`.

Hi @zwwhdls ,
Because the mount point is `/jfs/share` and `/data` in tools(app) container equals the parent folder of `/jfs/share`, so it shows the `/data/share` as the mount point?

```
containers:
    - name: app
    volumeMounts:
      - mountPath: /data
        name: shared-data
        mountPropagation: Bidirectional
...
    - name: jfs-mount
    volumeMounts:
   # juice mount point /jfs/share
    - mountPath: /jfs
      name: shared-data
      mountPropagation: Bidirectional
...
  volumes:
  - name: shared-data
    emptyDir:
      medium: Memory
...
```

After chanaged the moutPath of jfs-mount container from `/jfs` to `/jfs/share`, the mount point in tools (app)container is `/data`

```
[root@juicefs-app-sidecar-emptydir-memory2 /]# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   50G   24G   27G  48% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     16G     0   16G   0% /sys/fs/cgroup
JuiceFS:mcjfs1           1.0P  2.1G  1.0P   1% /data
/dev/mapper/centos-root   50G   24G   27G  48% /etc/hosts
shm                       64M     0   64M   0% /dev/shm
tmpfs                     32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount
```

**Comment by zwwhdls** [comment]
It's impossible and not make sense. If the pod config is as you showed above, the mount point in app container should be `/data/share` not `/data`. Please check it again carefully.

**Comment by enuoCM** [comment]
@zwwhdls 
Yes, I double checked the pod config:

```
containers:
    - name: app
    volumeMounts:
      - mountPath: /data
        name: shared-data
        mountPropagation: Bidirectional
...
    - name: jfs-mount
    volumeMounts:
   # juice mount point /jfs/share
   # /bin/mount.juicefs ${metaurl} /jfs/share -o metrics=0.0.0.0:9567
    - mountPath: /jfs/share
      name: shared-data
      mountPropagation: Bidirectional
...
  volumes:
  - name: shared-data
    emptyDir:
      medium: Memory
...
```

the result in app container:
```
[root@juicefs-app-sidecar-emptydir-memory2 /]# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   50G   24G   27G  48% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     16G     0   16G   0% /sys/fs/cgroup
JuiceFS:mcjfs1           1.0P  2.1G  1.0P   1% /data
/dev/mapper/centos-root   50G   24G   27G  48% /etc/hosts
shm                       64M     0   64M   0% /dev/shm
tmpfs                     32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount

[root@juicefs-app-sidecar-emptydir-memory2 /]# ls /data/
pvc-ae8b8177-8be7-4a70-80d9-6ef69ff95bbd
```

the result in jfs-mount container:
```
root@juicefs-app-sidecar-emptydir-memory2:/# df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   50G   24G   27G  48% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                     16G     0   16G   0% /sys/fs/cgroup
JuiceFS:mcjfs1           1.0P  2.1G  1.0P   1% /jfs/share
/dev/mapper/centos-root   50G   24G   27G  48% /var/jfsCache
tmpfs                     32G  4.0K   32G   1% /root/.rsa
shm                       64M     0   64M   0% /dev/shm
tmpfs                     32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount

root@juicefs-app-sidecar-emptydir-memory2:/# ls jfs/share/
pvc-ae8b8177-8be7-4a70-80d9-6ef69ff95bbd
```

mountPath `/jfs/share` in jfs-mount =  mountPath`/data` in app
