### ISSUE TITLE
[FEATURE] Support resources template in StorageClass

### ISSUE THREAD

**Issue by teddy-hackle** [juicedata/juicefs-csi-driver#853]
**What feature you'd like to add:**

In the case of pathPattern or mount Options, you can refer to PVC's annotment as ${PVC.annotations....} but cannot refer to options such as mount-cpu-limit, so you need to create a new Storage Class every time you modify the mound pod option.
It would be convenient if the above options could also be used by referring to PVC's annotments.

AS-IS(Current)

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.annotations['csi.juicefs.com/secret-name']}
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.annotations['csi.juicefs.com/secret-name']}
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/controller-expand-secret-name: ${pvc.annotations['csi.juicefs.com/secret-name']}
  csi.storage.k8s.io/controller-expand-secret-namespace: ${pvc.namespace}
  juicefs/mount-cpu-limit: 1000m
  juicefs/mount-memory-limit: 1Gi
  juicefs/mount-cpu-request: 500m
  juicefs/mount-memory-request: 500Mi
  juicefs/mount-delete-delay: "1m"

  pathPattern: "${.PVC.annotations.csi.juicefs.com/subdir}"
allowVolumeExpansion: true
reclaimPolicy: Delete
mountOptions:
  - ${.PVC.annotations.csi.juicefs.com/additional-mount-options}
```

TO-BE(Wanted)

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.annotations['csi.juicefs.com/secret-name']}
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/node-publish-secret-name: ${pvc.annotations['csi.juicefs.com/secret-name']}
  csi.storage.k8s.io/node-publish-secret-namespace: ${pvc.namespace}
  csi.storage.k8s.io/controller-expand-secret-name: ${pvc.annotations['csi.juicefs.com/secret-name']}
  csi.storage.k8s.io/controller-expand-secret-namespace: ${pvc.namespace}
  juicefs/mount-cpu-limit: ${pvc.annotations['csi.juicefs.com/mount-cpu-limit']}
  juicefs/mount-memory-limit: ${pvc.annotations['csi.juicefs.com/mount-memory-limit']}
  juicefs/mount-cpu-request: ${pvc.annotations['csi.juicefs.com/mount-cpu-request']}
  juicefs/mount-memory-request: ${pvc.annotations['csi.juicefs.com/mount-memory-request']}
  juicefs/mount-delete-delay:  ${pvc.annotations['csi.juicefs.com/mount-delete-delay']}

  pathPattern: "${.PVC.annotations.csi.juicefs.com/subdir}"
allowVolumeExpansion: true
reclaimPolicy: Delete
mountOptions:
  - ${.PVC.annotations.csi.juicefs.com/additional-mount-options}
```

**Why is this feature needed:**

The required resources for the mount pod vary depending on the characteristics of the PVC you use.
Like other options, if the option of the mount pod can be set in the pvc, I think it can be used flexibly.
