### ISSUE TITLE
[Proposal] use CRD to quickly enable more features

### ISSUE THREAD

**Issue by zxh326** [juicedata/juicefs-csi-driver#904]
### Objective:

let users to quickly create a resource to use some features, such as warming up data, creating cache group clusters.

### Example:

- Warrmup

ref: https://github.com/juicedata/juicefs-csi-driver/issues/872

In a certain scenario, users need to pre-warm one or more data.

The following resources can be created:

```yaml
apiVersion: csi.juicefs.com/v1
kind: Warmup
metadata:
  name: app-warmup
  namespace: default
spec:
  pv: xxxx
  concurrent: 50
  cachegroup: xx
```

Then we will create a task to execute this plan. 

- Create cache group clusters.
TBD

- Sync
TBD

- Schedule some jobs
TBD
