### ISSUE TITLE
pathPattern没起作用

### ISSUE THREAD

**Issue by pulsarrrr** [juicedata/juicefs-csi-driver#931]
在我的k8s集群使用helm chart：juicefs-csi-driver-0.19.8，按照官方文档添加pathPattern并没有起作用，还是默认命名。
k8s版本：1.22.17
类似于pvc-67f7c4fb-136a-4ea6-b3ec-1c9c549a71c9-emplmr
以下是我的values文件：
```
image:
  repository: juicedata/juicefs-csi-driver
  tag: "v0.23.5"
  pullPolicy: "IfNotPresent"

dashboardImage:
  repository: juicedata/csi-dashboard
  tag: "v0.23.5"
  pullPolicy: "IfNotPresent"

sidecars:
  livenessProbeImage:
    repository: quay.io/k8scsi/livenessprobe
    tag: "v1.1.0"
    pullPolicy: "IfNotPresent"
  nodeDriverRegistrarImage:
    repository: quay.io/k8scsi/csi-node-driver-registrar
    tag: "v2.1.0"
    pullPolicy: "IfNotPresent"
  csiProvisionerImage:
    repository: quay.io/k8scsi/csi-provisioner
    tag: "v1.6.0"
    pullPolicy: "IfNotPresent"
  csiResizerImage:
    repository: quay.io/k8scsi/csi-resizer
    tag: "v1.0.1"
    pullPolicy: "IfNotPresent"

mountMode: mountpod #process或者sidecar

# JuiceFS mount directory
jfsMountDir: /var/lib/juicefs/volume
# JuiceFS config directory
jfsConfigDir: /var/lib/juicefs/config

storageClasses:
- name: juicefs-sc
  enabled: true
  reclaimPolicy: Retain
  backend:
    name: "myjfs"
    metaurl: ""
    storage: "minio"
    accessKey: ""
    secretKey: ""
    bucket: ""
  pathPattern: "${.pvc.namespace}-${.pvc.name}"


dashborad:
  hostNetwork: true

```
我是否遗漏相关配置？

Thanks in advanced!
