### ISSUE TITLE
[BUG] 动态分配情况下对子目录进行配额嵌套分配失败

### ISSUE THREAD

**Issue by LOMOGO** [juicedata/juicefs-csi-driver#967]
**What happened**:
我在使用 storageclass 动态创建 pv-pvc 并使用 pathpattern 设置具有父子关系的目录两个 storageclass 时发现，即使我分别对这些具有父子关系的目录进行目录配额，但是他们最终能使用的配额都等于 父目录 的配额。
当父目录的配额小于子目录的配额时，在挂载了子目录的 pod 中执行 df -h 时会发现挂载的存储的容量等于父目录。
当父目录的配额大于子目录的配额时，使用 df -h 查看容量分配是正常的。

不管父目录的配额是否大于子目录，最终在使用时，父目录的配额限制都限制了所有的子目录的限额，这与官网文档的描述不一致，所以我认为这可能是一个bug， 或者我的理解有错误（因为我感觉所有子目录的内容不能超过父目录的限额也是非常合理的），希望能得到您的回复，谢谢：
<img width="986" alt="image" src="https://github.com/juicedata/juicefs-csi-driver/assets/46417831/b0c025e4-5ba4-4d3f-beaa-3dcaa336163a">

**What you expected to happen**:
希望在嵌套配额时，每个目录能够使用的配额与配置的配额有关，而不是等于父目录的配额

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: root-sc
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-root-minio-secret
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs-system
  csi.storage.k8s.io/node-publish-secret-name: juicefs-root-minio-secret
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs-system
  pathPattern: "/ai-plat"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tenant-sc
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-root-minio-secret
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs-system
  csi.storage.k8s.io/node-publish-secret-name: juicefs-root-minio-secret
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs-system
  pathPattern: "/ai-plat/${.pvc.name}"
---
# pvc 如下：
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      # 从 StorageClass 中申请 10GiB 存储容量
      storage: 10Gi
  storageClassName: root-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-tenant-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      # 从 StorageClass 中申请 6GiB 存储容量
      storage: 6Gi
  storageClassName: tenant-sc

---
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-root-app
  namespace: default
spec:
  containers:
  - args:
    - -c
    - sleep 3600
    command:
    - /bin/sh
    image: alpine
    name: app
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-tenant-app
  namespace: default
spec:
  containers:
  - args:
    - -c
    - sleep 3600
    command:
    - /bin/sh
    image: alpine
    name: app
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-tenant-pvc
```

**Anything else we need to know?**
我的业务场景是这样的：我的使用场景中存在很多个租户，每个租户能够使用的存储容量是需要硬限制的，并且存在一个管理员，可以看到所有租户的目录文件内容。并且可以针对该管理员的存储容量也进行一个容量限制
**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use): 0.24.0
- Kubernetes version (e.g. `kubectl version`): v1.21.14
- Object storage (cloud provider and region): minio
- Metadata engine info (version, cloud provider managed or self maintained): mysql
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 网络连接都正常
- Others: 无
